language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
install:
  - gradle spring-social-betaseries:check -x updateRootDocs --continue
  - gradle spring-social-betaseries:assemble -x updateRootDocs --continue
script: gradle spring-social-betaseries:build -x updateRootDocs --continue
