package org.springframework.social.betaseries.api;


/**
 * 
 * @author Guillaume Maka
 *	
 */
public enum BSTimelineEventType {
	FRIEND_ADD, FRIEND_DELETE, MARKAS, ADD_SERIE, DEL_SERIE, ARCHIVE,
    UNARCHIVE, RECOMMANDATION, RECOMMANDATION_DECLINE, RECOMMANDATION_ACCEPT,
    INSCRIPTION, UPDATE, SUBTITLES, COMMENT, BADGE, FORUM, WIKI, FILM_ADD, FILM_DEL,
    BANNER, SUGGEST
}
